import { chromium } from 'playwright';
const B = 'http://127.0.0.1:8899';
const ok = (n, c) => { console.log((c ? 'PASS' : 'FAIL ***') + ' · ' + n); if (!c) process.exitCode = 1; };
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const errs = [];
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
page.on('pageerror', e => errs.push(String(e).slice(0, 200)));
await page.goto(B + '/tickets.html');
await page.waitForTimeout(1500);
ok('no gate: page opens straight to the map', await page.$eval('#gate', g => g.hidden));
ok('mode chip says ON SALE NOW', await page.$eval('#modeChip', e => /ON SALE NOW/.test(e.textContent)));
ok('boot survived: zero page errors', errs.length === 0);
ok('59 holds arrive dark from the live store', await page.evaluate(() => unavailable.size) === 59);
ok('balcony repriced: config charges $38', await page.evaluate(() => CONFIG.prices.balc) === 38);
ok('buying page copy says Balcony $38', await page.evaluate(() => /Balcony[^$]*\$38/.test(document.body.innerHTML)));
await page.evaluate(() => onSeatClick('H-101'));
await page.waitForTimeout(600);
ok('seat click works: H-101 selected + held', await page.evaluate(() => selected.has('H-101')));
const cart = await page.$eval('#totals', e => e.textContent.replace(/\s+/g, ' '));
console.log('cart:', cart); ok('cart itemizes seat + $3 fee + total', cart.includes('$66') && cart.includes('$69'));
const held = await page.evaluate(() => fetch('/api/seats-state').then(r => r.json()));
ok('server confirms the hold (buyer-blind)', held.unavailable.includes('H-101'));
const landHtml = await (await fetch(B + '/')).text();
ok('poster landing: one click to the chooser', /href="\/shows\.html"/.test(landHtml) && /poster\.jpg/.test(landHtml) && /CLICK HERE FOR TICKETS/.test(landHtml));
const showsHtml = await (await fetch(B + '/shows.html')).text();
ok('chooser: double enthroned + two solo doors', /ON SALE NOW/.test(showsHtml) && /href="\/tickets\.html"/.test(showsHtml) && /href="\/sagalow\.html"/.test(showsHtml) && /href="\/cannon\.html"/.test(showsHtml));
const pressHtml = await (await fetch(B + '/press/')).text();
ok('press page: essentials, bios, downloads, contact, split pricing', /PRESS &amp; MEDIA/.test(pressHtml) && /BRENDAN SAGALOW/.test(pressHtml) && /MIKE CANNON/.test(pressHtml) && /JASON CHOI/.test(pressHtml) && /poster-high-res\.jpg/.test(pressHtml) && /bios\.pdf/.test(pressHtml) && /\$38/.test(pressHtml) && /\$24/.test(pressHtml) && /max@cape-cod\.co/.test(pressHtml) && /John Cafaro/.test(pressHtml));
const pAsset = await fetch(B + '/press/poster-high-res.jpg');
ok('press downloads resolve: high-res poster serves whole', pAsset.status === 200 && (await pAsset.arrayBuffer()).byteLength === 19588439);
const solo = await browser.newPage({ viewport: { width: 1200, height: 900 } });
solo.on('pageerror', e => errs.push('solo: ' + String(e).slice(0, 200)));
await solo.goto(B + '/sagalow.html');
await solo.waitForTimeout(1500);
const soloHtml = await solo.content();
ok('solo page: every section priced upon landing', /ORCHESTRA \$55/.test(soloHtml) && /TIER 1 \$44/.test(soloHtml) && /TIER 2 \$33/.test(soloHtml) && /BALCONY \$24/.test(soloHtml));
ok('solo page: live map boots with holds dark', await solo.evaluate(() => document.querySelectorAll('#map .seat.sold').length) >= 59);
ok('solo page: seats are look-not-buy', await solo.evaluate(async () => { const el = document.querySelector('[data-id="H-101"]'); el.dispatchEvent(new Event('click')); await new Promise(r => setTimeout(r, 400)); return !el.classList.contains('sel') && /aren't on sale yet/.test(document.getElementById('toast').textContent); }));
await solo.click('.wl-tier[data-tier="balc"]');
ok('tier chip lights on pick', await solo.$eval('.wl-tier[data-tier="balc"]', b => b.classList.contains('on')));
await solo.fill('#wlEmail', 'solofan@test.local');
await solo.click('#wlGo');
await solo.waitForTimeout(900);
ok('solo page: waiting list takes the email under its own flag', await solo.$eval('#wlMsg', m => /in line for SAGALOW/.test(m.textContent)));
const legacy = await (await fetch(B + '/api/waitlist', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'oldclient@test.local', choice: 'cannon' }) })).json();
ok('tier-less POST still lands (old client)', legacy.ok === true);
const wlTally = await (await fetch(B + '/api/admin-api', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-admin-token': 'greenroom' }, body: JSON.stringify({ action: 'waitlist' }) })).json();
ok('tally files it under sagalow', wlTally.sagalow >= 1);
const fan = (wlTally.entries || []).find(e => e.email === 'solofan@test.local');
ok('tally carries the section: solofan queued BALCONY', !!fan && fan.tier === 'balc' && wlTally.sections.balc >= 1);
const old2 = (wlTally.entries || []).find(e => e.email === 'oldclient@test.local');
ok('tier-less entry reads as ANY', !!old2 && old2.tier === 'any');
const relic = (wlTally.entries || []).find(e => e.email === 'relic@test.local');
ok('stored legacy row parses: relic reads EITHER / ANY', !!relic && relic.choice === 'either' && relic.tier === 'any');
ok('cross tally: cannon column carries the ANY', wlTally.cross && wlTally.cross.cannon && wlTally.cross.cannon.any >= 1);
const compR = await (await fetch(B + '/api/admin-api', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-admin-token': 'greenroom' }, body: JSON.stringify({ action: 'marksold', seats: ['C-101'] }) })).json();
ok('comp issuance returns ticket sid + code', !!compR.sid && compR.sid.startsWith('comp_') && !!(compR.codes && compR.codes['C-101']));
const tix = await browser.newPage({ viewport: { width: 1100, height: 900 } });
await tix.goto(B + '/success.html?sid=' + encodeURIComponent(compR.sid));
await tix.waitForTimeout(2500);
const tixText = await tix.evaluate(() => document.body.innerText);
ok('comp ticket page renders: seat + code + COMPLIMENTARY, no NaN', /SEAT C-101/.test(tixText) && tixText.includes(compR.codes['C-101']) && /COMPLIMENTARY/.test(tixText) && !/NaN/.test(tixText));
const lockScan = await (await fetch(B + '/api/scan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: compR.codes['C-101'] }) })).json();
ok('door word required: wordless scan comes back LOCKED', lockScan.verdict === 'LOCKED');
const okScan = await (await fetch(B + '/api/scan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: compR.codes['C-101'], door: 'stagedoor' }) })).json();
ok('door word admits: first scan VALID with the seat', okScan.verdict === 'VALID' && okScan.seat === 'C-101');
const reScan = await (await fetch(B + '/api/scan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: compR.codes['C-101'], door: 'stagedoor' }) })).json();
ok('second scan of the same ticket says ALREADY IN', reScan.verdict === 'ALREADY IN' && reScan.seat === 'C-101');
await browser.close();
console.log('errors:', errs.length ? errs : 'none');
